name: GitHub Actions Nightly Build

on:
  push:
    branches:
      - main
jobs:
  build-and-pre-release:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - name: Install dependencies
        run: bun install
      - name: Build the project
        run: bun run dev
      - name: Prepare a release
        run: bun run release
      - name: Publish pre-release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: 'redaktool.zip'